### ISSUE TITLE
Cargo can't compile unit3d-announce

### ISSUE THREAD

**Issue by lol-powa** [HDInnovations/UNIT3D-Announce#3]
Hello there,

When launching **cargo build --release** it failed because of this error:

`   Compiling unit3d-announce v0.1.0 (/var/www/html/tracker/UNIT3D-Announce)
error: error returned from database: 1146 (42S02): Table 'unit3d.personal_freeleech' doesn't exist
  --> src/tracker/personal_freeleech.rs:22:36
   |
22 |           let personal_freeleeches = sqlx::query_as!(
   |  ____________________________________^
23 | |             PersonalFreeleech,
24 | |             r#"
25 | |                 SELECT
...  |
29 | |             "#
30 | |         )
   | |_________^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `sqlx::query_as` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unused import: `Context`
  --> src/tracker/personal_freeleech.rs:10:14
   |
10 | use anyhow::{Context, Result};
   |              ^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `unit3d-announce` (bin "unit3d-announce") generated 1 warning
error: could not compile `unit3d-announce` (bin "unit3d-announce") due to previous error; 1 warning emitted`

The table 'unit3d.personal_freeleech' is not include with UNIT3D.
Could you give me some help on how to make it work ?

Thanks.

**Comment by Roardom** [comment]
It's because this project hasn't been updated since https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/3304 was implemented. Feel free to submit a PR otherwise I'll get around to it eventually :-)

**Comment by Roardom** [comment]
Reminder that this project is still very experimental and not production ready. There have been other changes to UNIT3D that break this project as well, such as https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/3472 and https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2828

**Comment by lol-powa** [comment]
Hello Roardom,

Thanks a lot for such a quick answer.
I understand it's fully experimental, but I was curious to give it a try.

Can you tell me which Torrent Tracker Software is recommended for Unit3d ?

Best,

**Comment by Roardom** [comment]
The one included with UNIT3D can still handle ~250 announces/s/core on modern hardware. Unless you have more than 5 million peers or are trying to run it on a raspberry pi, the stock one will do just fine.

**Comment by lol-powa** [comment]
Ok, great !
Perfect answer. Of course it's not to play on a Raspberry but on a decent server.
I am planning to move from Gazelle to Unit3d and I need to be sure that I'll be able to make it run...
Have a nice day.
