### ISSUE TITLE
Consider peerid reuse

### ISSUE THREAD

**Issue by ungoogled1** [HDInnovations/UNIT3D-Announce#5]
While unlikely, it is theoretically possible that an old peer_id is reused for a new session, resulting in key collision (peer_id, user_id). This can cause the session download/upload delta to become negative/clamped because its compared to the previous sessions download/upload.

It can be useful to detect such a scenario by checking if the session up/down is lower than the stored peer. And resetting the session stats to reflect that this is a new session.

https://github.com/HDInnovations/UNIT3D-Announce/blob/bcce5b2af99eb9d22d5db87507f1c90924203ffd/src/announce.rs#L439

Also see Ocelot
https://github.com/WhatCD/Ocelot/blob/master/worker.cpp#L394

For completeness: Theoretically, there still is another collision possibility when a user has multiple clients that get the same peer_id.

**Comment by Roardom** [comment]
Thanks for this report.

Unfortunately, besides the peer id and key, there's not much information to differentiate two peers seeded by the same user and the same torrent.

Are you meaning for a case where a user has two sessions at once where the user id and torrent id are the same?

Or to keep track of a new session that reuses the same peer id, but also stops using the old session at the same time?

For the latter case, we could do something like this:

```diff
diff --git a/src/announce.rs b/src/announce.rs
index b668c31..9d40869 100644
--- a/src/announce.rs
+++ b/src/announce.rs
@@ -436,8 +436,17 @@ pub async fn announce(
 
                     // Calculate change in upload and download compared to previous
                     // announce
-                    uploaded_delta = queries.uploaded.saturating_sub(old_peer.uploaded);
-                    downloaded_delta = queries.downloaded.saturating_sub(old_peer.downloaded);
+                    if queries.uploaded > old_peer.uploaded
+                        || queries.downloaded > old_peer.downloaded
+                    {
+                        // User continues old session
+                        uploaded_delta = queries.uploaded - old_peer.uploaded;
+                        downloaded_delta = queries.downloaded - old_peer.downloaded;
+                    } else {
+                        // User has restarted their session but reused the same peer id
+                        uploaded_delta = queries.uploaded;
+                        downloaded_delta = queries.downloaded;
+                    }
 
                     updated_at = Some(old_peer.updated_at);
                 }

```

I'm not sure if the `p->announces++` in the code you linked is useful, it looks like in ocelot that stat is only written to and not read from, perhaps it's used internally for debugging purposes or keeping track of users abusing the announce interval.

**Comment by ungoogled1** [comment]
>Or to keep track of a new session that reuses the same peer id, but also stops using the old session at the same time?
Yes this is what I intended.

Your code example implements the Idea I was trying to convey, looks good.

Sorry about the `p->announces++`, I meant to reference the code block, I did not meant to specifically reference to that line.

**Comment by Roardom** [comment]
Perfect, thank you. I will implement this ASAP.
